## 1. Numpy
- Python에서 행렬, 벡터, 차원 등의 수학적인 계산을 편하게 할 수 있도록 돕는 라이브러리다.

In [1]:
%pip install numpy

In [3]:
import numpy as np

In [13]:
# 1차원 배열
arr1 = np.array([1,2,3])
arr1
type(arr1)
arr1.shape  # .shape 행열 확인 (3,)
arr1.ndim   # .ndim 차원 확인 1

1

In [14]:
# 2차원 배열
arr2 = np.array([[1,2,3],[1,2,3]])
arr2
type(arr2)
arr2.shape  # (2,3)
arr2.ndim   # 2

2

In [21]:
# ndarray 데이터 타입
arr3 = [1,2,'c']

arr3 = np.array(arr3)
arr3.dtype  # U21 : 최대 길이가 21인 문자열 데이터

arr4 = ['1','2','3']
arr4 = np.array(arr4)
arr4.dtype  # U1 : 최대 길이 1인 문자열 데이터
arr4 = arr4.astype(np.int64)   # array([1,2,3])
arr4.dtype  # int64

dtype('int64')

In [26]:
# ndarray 생성
arr = np.arange(10)

arr > 5 # array([False, False, False, False, False, False,  True,  True,  True, True]) → boolen indexing

arr[arr > 5]    # 결과 값만 확인 가능.

array([6, 7, 8, 9])

In [29]:
np.zeros((3,2))  # 영행렬 : 0만 있는 행렬
np.ones((3,2))  # 1만 있는 행렬

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
# reshape : 차원 변경
arr = np.arange(10)

arr.reshape(2,5)
# 행*열 값이 동일한 것만 차원 변경이 가능하다.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
# indexing & slicing
arr[0]
arr[0:5]

array([0, 1, 2, 3, 4])

In [39]:
# numpy 몇가지 예제
# Q.1 2차원 배열에서 행렬의 각 행 평균을 계산하는 코드를 작성
# np.mean()

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

arr.shape
print(arr)
# axis = 0 (열), axis = 1 (행), axis = 2 (채널)
np.mean((arr), axis=1, dtype="int64")

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2, 5, 8])

In [42]:
# Q2. 1차원 배열에서 짝수 인덱스의 값을 출력하는 코드를 작성
arr = np.array([1,2,3,4,5,6])

even_indexes = np.arange(0, arr.size, 2)
print(arr[even_indexes])

[1 3 5]


In [45]:
# Q3. 2차원 배열의 주 대각선 상에 있는 원소들을 출력하는 코드를 작성
# diag()
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

arr.shape
np.diag(arr)

array([1, 5, 9])

In [48]:
# Q4. 2차원 배열에서 각 열의 표준편차를 계산하는 코드를 작성
# 표준편차 : np.std()
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(np.std(arr)) # 값 전체에 대한 표준편차
np.std(arr, axis=0)

2.581988897471611


array([2.44948974, 2.44948974, 2.44948974])

In [50]:
# Q5. 1차원 배열에서 중앙값(median)을 계산하는 코드를 작성
# median()
arr = np.array([1,2,3,4,5])

np.median(arr)

3.0

In [52]:
# Q6. 1차원 배열에서 원소의 값이 5 이상인 것들만 출력하는 코드를 작성
# Boolean Indexing
arr = np.array([1,4,6,3,9,2,7,8])

print(arr >= 5)
print(arr[arr>=5])

[False False  True False  True False  True  True]
[6 9 7 8]


In [53]:
# Q7. 1차원 배열에서 원소의 값이 3 또는 5인 것들의 인덱스를 출력하는 코드를 작성
# where()
arr = np.array([1,3,5,2,4,6,3,5,7])

np.where((arr == 3)|(arr ==5))
# and : & / or : |

(array([1, 2, 6, 7]),)